## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: deployment
  labels:
    app: nginx
    type: deployment
spec:
  selector:
    matchLabels:
      app: nginx
      type: deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        type: deployment
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 10m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 64Mi
