apiVersion: v1
kind: Namespace
metadata:
  name: deployment
---
apiVersion: v1
kind: Namespace
metadata:
  name: configmap
---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: service
