{{- if .Values.secretFiles }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "6-helmchart.fullname" . }}-file
  labels: {{ include "6-helmchart.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secretFiles }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
