apiVersion: v1
kind: Service
metadata:
  name: {{ include "6-helmchart.fullname" . }}-internal
  labels: {{ include "6-helmchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{ include "6-helmchart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
