# Default values for example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

resources:
  limits:
    cpu: 10m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

service:
  type: ClusterIP
  port: 80

envConfig:
  hey: whats going on?
  important: environment var

secretFiles:
  tragedy.txt: |
    Did you ever hear the tragedy of Darth Plagueis The Wise?
    I thought not.
    It’s not a story the Jedi would tell you.
    It’s a Sith legend.
    Darth Plagueis was a Dark Lord of the Sith, so powerful and so wise he could use the Force to influence the midichlorians to create life…
    He had such a knowledge of the dark side that he could even keep the ones he cared about from dying.
    The dark side of the Force is a pathway to many abilities some consider to be unnatural.
    He became so powerful… the only thing he was afraid of was losing his power, which eventually, of course, he did.
    Unfortunately, he taught his apprentice everything he knew, then his apprentice killed him in his sleep.
    Ironic.
    He could save others from death, but not himself.
