## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-env
  namespace: configmap
  labels:
    app: nginx
    type: configmap
data:
  hey: whats going on?
  important: environment var
