## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-env
  namespace: configmap
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: configmap
data:
  hey: whats going on?
  important: environment var
