## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-service
  namespace: service
  labels:
    app: nginx
    type: service
spec:
  selector:
    matchLabels:
      app: nginx
      type: service
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        type: service
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 10m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 64Mi
          envFrom:
            - configMapRef:
                name: nginx-configmap-env
          volumeMounts:
            - name: config-volume
              mountPath: /etc/important/config
      volumes:
        - name: config-volume
          secret:
            secretName: nginx-secret-file
