## ref: https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-internal
  namespace: service
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: service
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
