## ref: https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
  namespace: service
  labels:
    app: nginx
    type: service
spec:
  type: NodePort
  selector:
    app: nginx
    type: service
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30100
