apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: pod
  labels:
    app: nginx
    type: pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
          name: http
      resources:
        limits:
          cpu: 10m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 64Mi
