apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: default
  labels:
    app: alpine
    type: pod
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sh", "-c", "apk add curl && sleep 3600"]
